### ISSUE TITLE
Live OBF download URL changed and breaks older OsmAndMapCreator releases

### ISSUE THREAD

**Issue by cmoffroad** [osmandapp/OsmAnd-tools#1002]
Looks like the 'Download Live' URL for live OBF updates has changed, as older OsmAndMapCreator versions can’t access these links anymore:  
https://download.osmand.net/download?aosmc=true&self=true&file=Thailand_asia_24_12_00.obf.gz  

I can’t upgrade to JDK 17 yet, which is required for the latest OsmAndMapCreator build:  
https://osmand.net/docs/versions/map-creator/  

Is there an older version that works with JDK 16 and supports the updated URLs?

**Comment by vshcherb** [comment]
problem with url we need to double check what's new url

**Comment by cmoffroad** [comment]
> Another url works https://download.osmand.net/download?aosmc=true&file=Thailand_asia_24_12_00.obf.gz

Redirects to and returns 404 Not Found: https://dl8.osmand.net/download?aosmc=true&file=Thailand_asia_24_12_00.obf.gz&region=thailand_asia&self=true

**Comment by RZR-UA** [comment]
The original URL is fixed and should work now:

`https://download.osmand.net/download?aosmc=true&self=true&file=Thailand_asia_24_12_00.obf.gz`
