### ISSUE TITLE
Please add FreeBSD native library to sqlite-jdbc jar file for OsmAndMapCreator

### ISSUE THREAD

**Issue by ibrawley** [osmandapp/OsmAnd-tools#106]
The sqlite-jdbc JAR file has native (.so/.dll) files for Mac, Linux and Windows.

However, FreeBSD is missing (and FreeBSD is my OS of choice). After working out which version of sqlite-jdbc this tool uses, I was able to manually add the FreeBSD native libraries to the JAR file and that does make OsmAndMapCreator work.

ivan.
--
Ivan Brawley

**Comment by vshcherb** [comment]
Please create pull-request if possible, we don't maintain sqlite-jdbc jar itself. It was taken from 3rd part site.
