### ISSUE TITLE
Different map language on different zoom

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/OsmAnd-tools#111]
The map is in different languages on different zoom levels.
Android 5.0
Samsung galaxy s5 (sm-g900f)
Scale 2km or less - Scale 5 km or more:

København - Kopenhagen
Esbjerg - Esberg
Ribe - Ripen
Korsør  - Korsör
Same effects with Frech - German names
![screenshot_2016-04-16-11-25](https://cloud.githubusercontent.com/assets/12711814/15293221/b44d9d1e-1b8f-11e6-9aa3-582c989f9347.jpg)
![screenshot_2016-04-16-11-26](https://cloud.githubusercontent.com/assets/12711814/15293222/b450de66-1b8f-11e6-8b80-42949da7648d.jpg)

**Comment by vshcherb** [comment]
It is expected base map using Device language but detailed maps is using local names. It is configurable.
