### ISSUE TITLE
New merge-address-index misses a lot of addresses

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/OsmAnd-tools#118]
The Netherlands have 99+% addresses and is split into regions so that's a very good test country.

When I take the last Netherlands_europe_2.road.obf from 25 April I have an address index as follows:
`1 Address data Netherlands_europe - 511644266 bytes`
`	1.1 Address part size=205280648 bytes`
`	1.3 Address part size=86126001 bytes`
`	1.2 Address part size=207011470 bytes`

In the last couple of days I have downloaded multiple versions of OsmAndMapCreator and run the `merge-address-index` on the Dutch regions using my own [scripts](https://github.com/hvdwolf/OsmAnd-AddressMaps), but the map index is much smaller and indeed a lot of address are missing.
`1 Address data Netherlands - 320020084 bytes`
`        1.1 Address part size=188116434 bytes`
`        1.2 Address part size=37626306 bytes`
`        1.3 Address part size=83142072 bytes`
Last used OsmAndMapCreator was from May 29th 15:30 from the [nightlies](http://download.osmand.net/latest-night-build/)

**Comment by rominf** [comment]
Thank you for reporting, @hvdwolf. We are actively working on this, `merge-address-index` is still under development.

**Comment by hvdwolf** [comment]
I know it is still under development. I simply wanted to create an issue ticket where both developers and test users can report progress and bugs.

To mention: postcode search doesn't work at all in the new merged maps, even though the map creation progress clearly shows the "postcode normalization" from e.g. "1234 AB" to "1234AB"

**Comment by vshcherb** [comment]
Yes, 
1) we do postcode normalization
2) main difference is related that road and full map were not generated for May in the Netherlands but were generated for regions.

**Comment by rominf** [comment]
> To mention: postcode search doesn't work at all in the new merged maps, even though the map creation progress clearly shows the "postcode normalization" from e.g. "1234 AB" to "1234AB"

@hvdwolf, postcode search seem to be working, at least on MapCreator nightly build. I've just tested it on Netherlands map and "1011DL" (was "1011 DL" before normalization) index. Please try again on latest versions of OsmAnd and MapCreator and report if the issue persists.

**Comment by hvdwolf** [comment]
Correct. Also in my version from 29 May. I had not rebooted my phone after I had copied a new address map to my phone. I now rebooted my phone and now postcode search works.
It was not that it could not find a postcode. It didn't do anything when tappping "Search place or postcode". This is also peculiar of course.
