### ISSUE TITLE
Feature request: Be able to use map part name instead of index number 

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/OsmAnd-tools#121]
Currently when working with inspector or utilities you need to specify the map parts by number like 
`inspector.sh ........ +1,2,3` or `inspector.sh ....... -2,4` or something alike.
It would be highly convenient if we could specify something like:
 `inspector.sh ....... +map,routing,poi,address`.
If inspector or utilies would find (all) segments with that name and do "something" with it: add,extract, merge, etc.

**Comment by vshcherb** [comment]
I would say Nice to Have because it still doesn't solve all use cases especially when map has multiple sections. I think using bash utilties and grep with inspector.sh output will make it more custom and require even less code.
