### ISSUE TITLE
tag user_defined does not seem to be recognised anymore

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/OsmAnd-tools#128]
I wanted to create another UK postcode poi file for the UK users but it seems the tag 
`<tag k="user_defined" v="postal_code"/>`
is not recognised anymore in/by OsmAndMapCreator.

Has that changed to `user_defined_other`?

**Comment by vshcherb** [comment]
It has slightly changed https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L3015. Please also use own poi_types.xml during conversion, I will be fine to pull a request with any suggested tag like "user_defined" if you can get it working with custom poi_types

**Comment by hvdwolf** [comment]
I understand your link, because that's why I asked for that "user_defined_other".
I already tried that one with `<tag k="user_defined_other" v="postal_code"/>`,but that didn't work either. 
And what do you mean with "Please also use own poi_types.xml during conversion"? Should I placea file like that in my OsmAndMapCreator folder?
As such I don't care what the tag is. As long as you can use it.

**Comment by xmd5a2** [comment]
poi_types is located here: OsmAndMapCreator-main/lib/OsmAnd-core.jar/net/osmand/osm/poi_types.xml

**Comment by hvdwolf** [comment]
Yes, I know that. But Victor mentioned "before conversion". 
If I use your solution it means "before compilation".
That folder is nowhere to be found in an installed version. Just like you can place other rendering styles and routing.xml in an OsmAnd folder I wanted to know whether I can put a special  poi_types.xml in the OsmAndMapCreator folder.
I don't want to compile a special OsmAndMapCreator. 
This `user_defined` worked in the past. We even have docs on osmand.net explaining how to use the tag `user_defined`.
So technically speaking we have a bug here.
But as mentioned before: I don't mind to use any other tag, but that combination `<tag k="user_defined_other" v="postal_code"/>` does not work and I don't want to compile another version simply because I want to help other UK users (being Dutch myself).
Please let me know which combination would work with the latest versions of OsmAndMapCreator.

**Comment by xmd5a2** [comment]
Just open jar as zip archive and put xml to it.

**Comment by hvdwolf** [comment]
OK. I will do that. I thought the jar was signed and could therefore not be changed.
