### ISSUE TITLE
More detail for basemap generation

### ISSUE THREAD

**Issue by longlostbro** [osmandapp/OsmAnd-tools#133]
For step 4 of Coastlines it mentions to manually fix all 180 degree breaks. Could you explain in more detail? What program is used? josm? or just an editor? how many changes are to be fixed?

How does one "simply divide islands into 2 islands and add connect line on 180 degree) and make Antarctica cycled."?

https://github.com/osmandapp/OsmAnd-tools/tree/master/obf-generation/basemap
Coastlines
1. Download ne_10m_coastline.zip from http://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-coastline/
2. Unzip it
3. Locate and run 'shp2osm.pl' script as should below:
   perl ./shp2osm.pl ./ne_10m_coastline.shp | sed 's/FeatureCla/natural/g;s/Coastline/coastline/g' > ./ne_10m_coastline.osm 
4. Fix manually all 180 degrees breaks (simply divide islands into 2 islands and add connect line on 180 degree) and make Antarctica cycled.

**Comment by vshcherb** [comment]
I think it was josm we modified it in osm file and have all downloads available here http://builder.osmand.net/basemap/

**Comment by longlostbro** [comment]
Thank you. Thats exactly what i needed.

**Comment by longlostbro** [comment]
Which of the osm.bz2 files from http://builder.osmand.net/basemap/ are used in the creation of World_basemap_2.obf?
I'm trying to get an osm.pbf exactly like your World_basemap_2.obf

**Comment by xmd5a2** [comment]
proc_*.osm.bz2
