### ISSUE TITLE
Maps created with OsmAndMapCreator don't have the elevation/slope profile

### ISSUE THREAD

**Issue by naoliv** [osmandapp/OsmAnd-tools#136]
What exactly is needed to create maps with the elevation/slope profile, please?

I have tested right now with the latest `OsmAnd-default.apk` (`OsmAndF~ 2.6.0#17165D`) and with a freshly generated extract (also using the latest `OsmAndMapCreator-main.zip`) from here and I cannot see any elevation/slope profile while clicking at the information place.

For example, with my own generated map:
![](https://cloud.githubusercontent.com/assets/982338/25088683/7648d9ee-234e-11e7-843a-a7370c596d07.png)

And the same route, but using osmand's `Brazil São Paulo` (from March 31):
![](https://cloud.githubusercontent.com/assets/982338/25088688/7dfb6440-234e-11e7-87a6-429f6a4bd604.png)

So it seems clear that osmand's map has something that my own generated map doesn't have.

Basically I am creating the map in batch mode with:

`java -cp "./OsmAndMapCreator.jar:./lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.data.index.IndexBatchCreator batch.xml`

Where `batch.xml` has:

```xml
<?xml version="1.0" encoding="utf-8"?>
<batch_process>
        <process_attributes mapZooms="" renderingTypesFile="" zoomWaySmoothness=""
                osmDbDialect="sqlite" mapDbDialect="sqlite"/>

        <!-- There are 3 subprocess :
                 1. Download fresh osm files from servers to 'directory_for_osm_files' (override existings).
                 2. Generate index files from all files in 'directory_for_osm_files' and put all indexes into 'directory_for_index_files'
                 3. Upload index files from 'directory_for_index_files' to googlecode.
                 If directory directory_for_uploaded_files is specified all uploaded files will be moved to it
                 All these subprocess could be ran independently ! So you can create some files check them and after that try to upload on googlecode,
                 or you can upload any file you have to googlecode (just put into 'directory_for_index_files')
         -->
         <!-- zoomWaySmoothness - 1-4, typical mapZooms - 11;12;13-14;15-   -->
         <process directory_for_osm_files="/home/naoliv/mapa/osm" directory_for_index_files="/home/naoliv/mapa/mapa" directory_for_generation="/arquivos/tmp"
                 skipExistingIndexesAt="/arquivos/tmp" indexPOI="true" indexRouting="true" indexMap="true"      indexTransport="true" indexAddress="true">
                <!-- Add wget="C:/Program Files/GNUWin32/bin/wget.exe" to process, to use wget for download.
                         On linux systems if wget is in your path it can be wget="wget" or you can make own script with wget command:
                         wget="/path/to/script/wget.sh"
                         Defaultly enabled parameter of wget is: &-&-read-timeout=5 that prevents hanging of download from  cloudmade/geofabrik server
                -->

        </process>
</batch_process>
```

ie, it's basically the vanilla `batch.xml` with modified paths only.

What I am missing here to create maps with a elevation/slope profile, please?

**Comment by xmd5a2** [comment]
SRTM/ASTER/EU-DEM tiffs are needed. You can download them here http://download.osmand.net/srtm/srtm_osmand.torrent
There is two ways of using them: dropping to "osmand/srtm" folder and use OsmAndMapCreator GUI, or add
```
directory_for_srtm_files="path_to_srtm"
```
to "process" tag in your batch.xml
Check can be done using inspector
```
./inspector.sh -vrouting file_name.obf | grep osmand_ele
```
If you see massive output then elevation data is ok.

**Comment by naoliv** [comment]
Thanks for the answer.

I see no peers here to download the files from your torrent.
I guess I can directly download the files that I need from https://earthexplorer.usgs.gov/ without any problem?

Also, maybe [batch.xml](https://github.com/osmandapp/OsmAnd-tools/blob/master/OsmAndMapCreator/src/net/osmand/data/index/batch.xml) should be updated to include the info about `directory_for_srtm_files` too?

**Comment by xmd5a2** [comment]
Try this link http://builder.osmand.net/terrain-aster-srtm-eudem/ . I do not recommend trying other SRTM data sources because OsmAndMapCreator will correctly work only with Int16 Tiffs and properly named.

**Comment by naoliv** [comment]
Right. I am downloading the files.

**Comment by vshcherb** [comment]
Issue was investigated. The files also could be located in the working folder under subdirectory called "srtm".

**Comment by xmd5a2** [comment]
Another way to download these tiffs https://rutracker.org/forum/viewtopic.php?t=5393970

**Comment by naoliv** [comment]
The TIFFs from http://builder.osmand.net/terrain-aster-srtm-eudem/ are the same from https://rutracker.org/forum/viewtopic.php?t=5393970 ?

**Comment by xmd5a2** [comment]
Yes, exactly

**Comment by naoliv** [comment]
Right. Thank you!
