### ISSUE TITLE
building obf from  osm doesn't work

### ISSUE THREAD

**Issue by ShinIce** [osmandapp/OsmAnd-tools#137]
Hi there,

not really sure where this "bug" suits better but I would get rid of it.

Some facts:
CSV: 220M
OSM: 1,3G
OBF: 62bytes

The csv was convertet with gpsbabel to osm and the file looks great, next step was the conversion of the osm to obf but it fails.
Convert was startet on debian sid, mac os sierra and windows, but every time the same file pops out.

Last line from the osmand log:
Apr 25, 2017 3:40:01 PM net.osmand.swing.ProgressDialog startTask
FEIN: Memory before task exec: 1658322944 free : 462941256
Apr 25, 2017 3:40:01 PM net.osmand.swing.ProgressDialog startTask
FEIN: Indiziere Grenzen aus Relationen … started after 101253 ms
Apr 25, 2017 3:40:44 PM net.osmand.swing.ProgressDialog startTask
FEIN: Memory before task exec: 1658322944 free : 459952784
Apr 25, 2017 3:40:44 PM net.osmand.swing.ProgressDialog startTask
FEIN: Verarbeite OSM Knoten … started after 42646 ms
Apr 25, 2017 3:41:20 PM net.osmand.swing.ProgressDialog startTask
FEIN: Memory before task exec: 1744306176 free : 712278456
Apr 25, 2017 3:41:20 PM net.osmand.swing.ProgressDialog startTask
FEIN: Verarbeite OSM Wege … started after 36745 ms
Apr 25, 2017 3:41:20 PM net.osmand.swing.ProgressDialog startTask
FEIN: Memory before task exec: 1744306176 free : 709006384
Apr 25, 2017 3:41:20 PM net.osmand.swing.ProgressDialog startTask
FEIN: Verarbeite OSM Relationen … started after 154 ms
Apr 25, 2017 3:41:21 PM net.osmand.swing.ProgressDialog startTask
FEIN: Memory before task exec: 1744306176 free : 705776744
Apr 25, 2017 3:41:21 PM net.osmand.swing.ProgressDialog startTask
FEIN: Writing poi index to binary file... started after 194 ms
Apr 25, 2017 3:41:21 PM net.osmand.impl.ConsoleProgressImplementation startWork
INFORMATION: Task null: work total has changed to 1000000
Apr 25, 2017 3:41:21 PM net.osmand.data.preparation.IndexPoiCreator processPOIIntoTree
INFORMATION: Poi processing finished
Apr 25, 2017 3:41:21 PM net.osmand.data.preparation.IndexPoiCreator writeBinaryPoiIndex
INFORMATION: Poi box processing finished
Apr 25, 2017 3:41:21 PM net.osmand.data.preparation.BinaryMapIndexWriter endWritePoiIndex
INFORMATION: POI INDEX SIZE : 44
Apr 25, 2017 3:41:21 PM net.osmand.data.preparation.IndexCreator generateIndexes
INFORMATION: Finish writing binary file

Any idea/hint/somethin to test?

Thanks :)
Shin

**Comment by xmd5a2** [comment]
osm file should contain tags supported by OsmAnd (see resources/rendering_types.xml)

**Comment by ShinIce** [comment]
good point, thanks, forgot the sample xD

example from the csv (fake coord)
Latitude,Longitude,Name
12.345678,12.345678,Geocache1

example from the osm (fake coord)
<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' generator='GPSBabel-1.5.3'>
  <node id='-1' visible='true' lat='12.345678' lon='12.345678'>
    <tag k='created_by' v='GPSBabel-1.5.3'/>
    <tag k='name' v='Geocache1'/>
    <tag k='note' v='Geocache1'/>
    <tag k='geocache' v='found'/>
  </node>

and as I can see geocache is in the rendering_types.xml:
	<category name="geocache">
		<type tag="geocache" value="found" minzoom="15" notosm="true"/>
		<type tag="geocache" value="not found" minzoom="15" notosm="true"/>
	</category>

**Comment by xmd5a2** [comment]
Your example gives this obf
```
./inspector.sh -vmap -vmapobjects /home/xmd5a/osmand/Test_issue_2.obf
мая 04, 2017 4:14:21 PM net.osmand.osm.MapPoiTypes initFromInputStream
INFO: Time to init poi types 45
Binary index Test_issue_2.obf version = 2 edition = Thu May 04 16:12:17 MSK 2017
1 Map data Test_issue - 364 bytes
	1.1 Map level minZoom = 15, maxZoom = 22, size = 107 bytes 
		Bounds (left top - right bottom) : 12.3457, 12.3457 NE - 12.3457, 12.3457 NE
	1.2 Map level minZoom = 13, maxZoom = 14, size = 83 bytes 
		Bounds (left top - right bottom) : 12.3457, 12.3457 NE - 12.3457, 12.3457 NE
	1.3 Map level minZoom = 12, maxZoom = 12, size = 83 bytes 
		Bounds (left top - right bottom) : 12.3457, 12.3457 NE - 12.3457, 12.3457 NE
**Point types [geocache-found (4)] Names [name(1) - Geocache1] id -2 osmid -1**
Point types [note_tag-yes (3)] Names [note(2) - Geocache1] id 2199023255488 osmid 17179869183
мая 04, 2017 4:14:21 PM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Search is done. Visit 2 objects. Read 2 objects.
мая 04, 2017 4:14:21 PM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Read 1 subtrees. Go through 2 subtrees.
	Total map objects: 2
2 Routing data Test_issue - 12 bytes
	Bounds (left top - right bottom) : 180, -90 NE - -180, 90 NE
3 Address data Test_issue - 57 bytes
	3.1 Address part size=2 bytes
	3.3 Address part size=2 bytes
	3.2 Address part size=2 bytes
4 Poi data Test_issue - 42 bytes
5 Transport data Test_issue - 82 bytes
	Bounds (left top - right bottom) : -180, 85.0511 NE - -180, 85.0511 NE
```
It means that data is in obf

**Comment by ShinIce** [comment]
Ok, so there must be somewhere else the problem, but I can't find it.

```
./inspector.sh -vmap -vmapobjects geocaches.obf
Mai 04, 2017 3:22:13 PM net.osmand.osm.MapPoiTypes initFromInputStream
INFORMATION: Time to init poi types 94
Binary index geocaches.obf version = 2 edition = Sun Apr 23 12:59:22 CEST 2017
1 Poi data Worldportals - 44 bytes
```

Could it be that my osm file is "to big" with 1.3G? Maybe I'm missing a step: I only flag "make POI index" and then I load the osm file.
I'm doing another run right now and will post the output as soon I have it.

**Comment by xmd5a2** [comment]
If you flag only POI then you'll get only POI. If you need these objects as POI then you need to edit poi_types.xml which is in OsmAndMapCreator-main/lib/OsmAnd-core.jar/net/osmand/osm/poi_types.xml

**Comment by ShinIce** [comment]
well, this is strange, I still get the same file.
I'm going to clean up all and fetch the MapCreator again.

I'm getting crazy building this stuff >.<

**Comment by ShinIce** [comment]
clean install did the trick.
took a little bit to build (1,3G osm -> 750mb obf) but works.

Thank you for the hint 

> OsmAndMapCreator-main/lib/OsmAnd-core.jar/net/osmand/osm/poi_types.xml

I think this should be added in the faq to or at least let the mapcreator throw an error for "missing poi type" or somethin link that.
