### ISSUE TITLE
ClassNotFoundException: net.osmand.data.index.IndexBatchCreator

### ISSUE THREAD

**Issue by naoliv** [osmandapp/OsmAnd-tools#249]
Did something change when creating maps in batch, please?

I always used this:
```
java -cp "./OsmAndMapCreator.jar:./lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.data.index.IndexBatchCreator batch.xml
```

But now it's giving an error:

```
Error: Could not find or load main class net.osmand.data.index.IndexBatchCreator
Caused by: java.lang.ClassNotFoundException: net.osmand.data.index.IndexBatchCreator
```

It seems to be happening since Jun 16

**Comment by astavale** [comment]
Try `net.osmand.util.IndexBatchCreator`:

```
java -cp "./OsmAndMapCreator.jar:./lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml
```

I found that by trying the `generate-obf-files-in-batch` command of `net.osmand.MainUtilities` and found it in the stack trace I got when I ran out of memory:

```
java -cp "./OsmAndMapCreator.jar:./lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.MainUtilities generate-obf-files-in-batch batch.xml
```

I'm trying to build a map from a 1.5GB OSM PBF file of the Netherlands and a bit of the bordering countries. Keep running out of memory at about 20% even after allocating 10GB. Any tips? May be create smaller OBFs? I don't know how OSMAnd works stitching those together.

**Comment by naoliv** [comment]
@astavale it did work with `net.osmand.util.IndexBatchCreator`, thanks!

Did you try changing `sqlite_in_memory` to `sqlite` in https://github.com/osmandapp/OsmAnd-tools/blob/master/obf-generation/indexes-batch-generate-inmem.xml#L4?

-----
For the developers, probably it's needed to update the instructions in https://osmand.net/help/TechnicalArticles.html and somewhere else (replacing `net.osmand.data.index.IndexBatchCreator` by `net.osmand.util.IndexBatchCreator`)

**Comment by astavale** [comment]
For the documentation it may be better to highlight the use of `net.osmand.MainUtilities` because this gives a wider range of commands. For Unix platform to use the batch creation method the command is:

```
./utilities.sh generate-obf-files-in-batch batch.xml
```

just
```
./utilities.sh 
```
shows the other options. Setting the environment variable `JAVA_OPTS` can be used to change the heap memory allocations. Unfortunately changing to `sqlite_in_memory` to `sqlite` didn't work in my case.

For Windows there is `utilities.bat`.

**Comment by vshcherb** [comment]
@astavale Thanks for comment this is exactly how it is intended to be used now.
