### ISSUE TITLE
Make maxspeed* and possibly other tags a valid "change" for osm-live maps

### ISSUE THREAD

**Issue by skylerbunny** [osmandapp/OsmAnd-tools#275]
I _think_ I have the right repo here. Some of the code I found like https://github.com/osmandapp/OsmAnd-tools/tree/master/obf-generation/basemap looks like what might be used to generate osm-live diff maps for OsmAnd+. If I'm wrong, please let me know which repo this belongs in.

Through trial and error I believe I figured out that there's a subset of changes that will actually trigger a 'This way changed; add it to the osm-live map diff'. It looks something like this:

* Geometry changes to a way in terms of the number of or ids of its nodes (or a change to one of its child nodes?)
* The name of the way
* The ref of the way

If none of the above changes and I change a way's maxspeed (or maxspeed:forward, maxspeed:backward, etc.), or the turn:lanes on a way, that change won't be seen in osm-live maps. I'd like to suggest that there are additional tags that are important enough that they also should be flagged in queries to generate osm-live maps as a "change" that requires a refreshed way.

These include (that I believe OSMand uses to create routing instructions or guidance in the first place, and now osm-live advertises itself as being able to route using said map updates):
* destination[:lanes]*
* maxspeed[:forward|:backward]
* turn:lanes[:forward|:backward]
* Others?

There may be others, but this would be a really good guess at adding some of them. It not only increases the value of the osm-live map substantially because more information is added more frequently that OsmAnd+ will use on the spot, but it allows spot checking by power-editors (make a change, wait two hours, see if the change visually does what the person thought it does).

What drew me here was the realization that maxspeed=* was being added to many intermediate ways in the osm-live map after I did a survey from beginning to end -- but not all of the intermediate ways -- and that I think the ones that didn't get a change were "because the only thing I changed on that way was the maxspeed tag".

**Comment by vshcherb** [comment]
This is not a "correct" repo cause we don't look at issues here (as users report mostly in OsmANd). Anyway basemap is not involved into OsmAnd Live at all, so it is not an issue. 
OsmAnd live generates exactly maps as detailed so all the tags should be present. You can check osmand live file with binary inspector (part of OsmAndMapCreator utilities) and see them .
Live Files: http://download.osmand.net/aosmc/
