### ISSUE TITLE
How to create maps with OsmAndMapCreator from command line?

### ISSUE THREAD

**Issue by stefanodroghetti** [osmandapp/OsmAnd-tools#310]
Some time ago I used to do like this:

java -Djava.util.logging.config.file=logging.properties -Xms128M -Xmx2000M -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.data.index.IndexBatchCreator ./batch.xml

Where "batch.xml" is a file where I store all the folder patches (where to put the final map, where is the .pbf map, and so on)

But with the new versions of OsmAndMapCreator lot of things changed: there is no more OsmAnd-core.jar in lib folder, there is no more lib-gl folder, and so on.
So if I launch the old command, it returns an "unable to find main class net.osmand.data.index.IndexBatchCreator" error.

I can't find any documentation, and the wiki on OSM site doesn't seem to be updated since 2013.

**Comment by AndreasTUHU** [comment]
According to this thread you should use utilities.bat on Windows: 
https://github.com/osmandapp/OsmAnd-tools/issues/249

for example:
utilities.bat generate-obf-files-in-batch batch.xml

By the way it is not working for me. It cannot read the batch.xml, but I don't know why:
XML configuration file could not be read from batch.xml

**Comment by vshcherb** [comment]
Yes ```utilities.bat generate-obf-files-in-batch batch.xml``` it is a new way, it is part of utilities.sh documentation
