### ISSUE TITLE
taginfo project unavailable

### ISSUE THREAD

**Issue by goldfndr** [osmandapp/OsmAnd-tools#311]
The site mentioned at https://github.com/osmandapp/OsmAnd-tools/blob/master/obf-generation/taginfo.groovy#L87 is no longer available. The [taginfo projects fetch table](https://taginfo.openstreetmap.org/taginfo/projects) shows a result code of 500 for the site.

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd-tools/commit/b57724361541164482445294fd1b40038b12be29
