### ISSUE TITLE
Map compilation got too long with SRTM changes

### ISSUE THREAD

**Issue by naoliv** [osmandapp/OsmAnd-tools#320]
It seems that after some changes related with SRTM (https://github.com/osmandapp/OsmAnd-tools/commit/d931f2b3d9a1bd2b81cbe7d8e9745d236bd424c8 https://github.com/osmandapp/OsmAnd-tools/commit/f224b928142cc9ab75cc96f7ff5c2b5d10e78ce3 https://github.com/osmandapp/OsmAnd-tools/commit/7239ff6cbc5668133dc4da1eddfdc298098df02c https://github.com/osmandapp/OsmAnd-tools/commit/885cfde013ba75c2b10334da668557a54c23733b https://github.com/osmandapp/OsmAnd-tools/commit/6ad7d9c1702fa0dc40f8154e24f0b8c9789e6197 https://github.com/osmandapp/OsmAnd-tools/commit/a0753cbd0f47e5dfefb2bcd07e34c8d50283db13 https://github.com/osmandapp/OsmAnd-tools/commit/4efd099aa0169613cc63ff65426b71cd4821a00c https://github.com/osmandapp/OsmAnd-tools/commit/13d36601aabc8f22c6185ccc58e595c0ba4c319a) the building time of maps have increased a lot.

It took 4 hours only to process the SRTM part of this area https://www.openstreetmap.org/relation/298204, printing this every 1 second it seems:

```
INFO: SRTM: Load srtm data 136258: -24 -47
jul 22, 2019 4:45:14 AM net.osmand.obf.preparation.IndexHeightData getPointHeight
INFO: SRTM: Load srtm data 136259: -23 -47
jul 22, 2019 4:45:16 AM net.osmand.obf.preparation.IndexHeightData getPointHeight
INFO: SRTM: Load srtm data 139334: -20 -44
jul 22, 2019 4:45:18 AM net.osmand.obf.preparation.IndexHeightData getPointHeight
INFO: SRTM: Load srtm data 138310: -20 -45
(...)
```

Maybe there is something that could be optimized about this?

**Comment by vshcherb** [comment]
You didn't catch that commit - https://github.com/osmandapp/OsmAnd-tools/commit/5e9aeae9556046d3eb2f1f456bea1f761c0001b1#diff-cf71205ff0a9cf0c27db493d05b1b11e

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/f110634b00420748158f0fa521678765ab7a1b70 
Though the issue of course is open how to optimize it.
