### ISSUE TITLE
Sync Favorites

### ISSUE THREAD

**Issue by brunoschroeder** [osmandapp/OsmAnd-tools#327]
This is the #1 feature request I have for you. I have acquired your yearly version. I love your work! This tool is brilliant! I really lack an UX similar to googlemaps or maps.me.

Another important feature is a browser version of the UX.

Feature request: As a personal home user who has a photographic memory and spacial sense and perception, I would like to be able to have the same geo-bookmarks synced in my mobile openstreetmaps tool as well as in a browser web editor, so that I can improve and have more productivity on the creation and update of my bookmarks in both platforms.

**Comment by vshcherb** [comment]
1 issue would be enough, all feature request we maintain in ios/android repos
