### ISSUE TITLE
Task serializing_address 

### ISSUE THREAD

**Issue by mpele** [osmandapp/OsmAnd-tools#330]
I am trying to create obf file through batch process. 
It works, at the beginning, but then say something like:

> Oct 05, 2019 9:12:09 PM net.osmand.impl.ConsoleProgressImplementation startWorkLong
> INFO: Task serializing_address: work total has changed to 217

and than there are no new messages for very long time (I have been waiting for few hours).  The processor something works but there is no visible results. 
Pbf file that is processed is slight modification of file from the Geofabrik (removed lines from osm file with conditional maxspeed). 

What could be wrong, and how to find what is the problem?

**Comment by vshcherb** [comment]
It probably ran out of memory and start consuming most of time on garbage collecting, so it gets stuck. Please let us know which fild did you use and we can share our observation how much it takes to create

**Comment by mpele** [comment]
I have just tried with the newer pbf file and now it works fine :) . 
Thank you for your time !
