### ISSUE TITLE
Please consider including other addr:* keys like addr:place

### ISSUE THREAD

**Issue by bkil** [osmandapp/OsmAnd-tools#436]
Sometimes in certain areas, there are no streets or house numbers. There usually exist `addr:place` in such cases. It would be great if we long clicked on the map, this could also be shown to the user (and/or searched for), but first for this to work, it needs to be present in the created `obf`.

Here is an example:
* https://www.openstreetmap.org/way/851408221#map=17/46.74367/19.52269

**Comment by tommycrock** [comment]
What kind of object needs to be in OSM for the addr:place to work? For example I have added a landuse=residential called Crooklands [1] and added addr:place=Crooklands to a building within that area [2] yet the address does not seem to be stored.
![Screenshot_20220106-190958_OsmAnd+](https://user-images.githubusercontent.com/5749884/148438418-cb02763d-980a-4500-a0fd-09bf5a631a57.jpg)


1. https://www.openstreetmap.org/way/932618669 
2. https://www.openstreetmap.org/way/548577454

**Comment by vshcherb** [comment]
@tommycrock https://docs.osmand.net/en/main@latest/development/algorithms/trace-address-search-issues - please check here + similar issues there. I think it requires tag place but not all places are supported probably.
