### ISSUE TITLE
missing option to render hillshade database in OsmAndMapCreator offline rendering mode

### ISSUE THREAD

**Issue by cmoffroad** [osmandapp/OsmAnd-tools#467]
Is there a way to render the hillshade sqlite database in OsmAndMapCreator offline rendering mode ?
Or does the sqlite database needs to be converted into an OBF file ?

**Comment by vshcherb** [comment]
Nope it's not possible. OsmAndMapCreator doesn't even display laers, so I think it's not going to be supported
