### ISSUE TITLE
PBF files for map builder no longer available

### ISSUE THREAD

**Issue by Vascom** [osmandapp/OsmAnd-tools#658]
As described at maps build instruction pbf-files were previously available at https://builder.osmand.net/osm-extract/
But now this URL not work.

Please fix it or give new URL with pbf-files.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/web/commit/3cb0d59948401b4e74c918b00b75d0a14081e2be

**Comment by Vascom** [comment]
Thanks for the fix.
