### ISSUE TITLE
Request for Information: OsmAndMapCreator-Created Map Is Blank At High Zoom

### ISSUE THREAD

**Issue by linuxrocks123** [osmandapp/OsmAnd-tools#758]
I recently used OsmAndMapCreator to convert a custom PBF file I created to OBF format.  Navigation works, but the map itself looks completely blank if zoom in to 0.25 miles or closer.  At 0.5 miles and lower zoom levels, the map looks normal.

The "map totally blank" thing is happening right at the zoom level where you would expect to see the polygons representing houses and stuff like that.

I must be doing something wrong when using OsmAndMapCreator to convert from PBF to OBF.  Do you know what that might be?

**Comment by linuxrocks123** [comment]
Additional information: the map I created is for all of Texas.  The procedure I used to create the map was to set the Java memory to 24GB, open up the GUI, and select "Create OBF from OSM file...".  In case it matters, I did not use "Create OBF from OSM file for specified area".

**Comment by vshcherb** [comment]
You can use 
```./utilities.sh generate-obf to generate map ```
and also later check the contents of the file with ./inspector.sh it should have Map section and Routing section

**Comment by vshcherb** [comment]
You can use 
```./utilities.sh generate-obf to generate map ```
and also later check the contents of the file with ./inspector.sh it should have Map section and Routing section
